sudo: false
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler jekyll
before_script:
- chmod +x ./bin/setup
- "./bin/setup"
- bundle exec jekyll build
script: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension
  --check-opengraph --url-ignore "feed.xml,/facebook.com/"
after_success:
- chmod +x ./bin/automated
- "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - LC_ALL=en_US.UTF-8
  - JEKYLL_ENV=production
  - USERNAME: zhanghongjiang
  - EMAIL: mytiger@gmail.com
  - secure: jAQKQOkVnmaihZQqyQbCeBUDsI4PWi/vmpmeEUPJcSbg0UULI6eIXlbQec55OuMYhGpQlv6YuQ3AQQUP6Z3C8qJppRjb5sVxuFrlplb2NeKC9FuuMWvnjKMTAKn0SFoaX/NxSVuOqP7PFD/h2Zv/2Sl6kmILgJlCc073yNl0PylXQF3wNeWVM1VzxbP5BYK8iaqtvFgeWgc8FZpff46nLp/mCWHVfLGzCYVpKw76YTI6b2V8S/HxNRmF0CDIqzvEsyF9cDnEReKMH2cMaeeMHBscb2G+QCibAaq8omGnrE8Idcwa15UpsKYUQ2B45WnlONc+2rmtRGrB1lHi1XYUSASjr5z7nhtmutXw/po5U8Xf1O1Gx2T/mMxfQKptM0z4Xt6IfKGaHMJmAwApkFMqJuKJbmndNzs1Da7s9sknfR6Ce5Ogu/9PCCOhmq1OcZtlDqPpDBbXqNLIHLVAxlwAQKcRqxnYrFZYNM2RDAxjOPg0N7zpa/gstaA//zvGQPUuZtjKTDyZhtsgLuiLA5A8HDSNFaHMqm+2EcwcslxWmYdSouwT981pbp4JipkY8PAru8IuvNA/MvQTi+fJmaM1YwQ7UOFTcv+s5RvnGvm/L6cYQPpOcAuEUtH6WoPwJHlw4uext33nVXsiKrO6oN/If7giqxlszKznl+MTqIG+cbI=
